### ISSUE TITLE
Validate should also work if tag is not the first one 

### ISSUE THREAD

**Issue by sharpner** [go-validator/validator#17]
If I got a struct like this

```go
type NewUserRequest struct {
    Username string `db:'user_name' validate:"min=3,max=40,regexp=^[a-zA-Z]$"`
}
```

The validation for user name will always be correct, but if I change it to:

```go
type NewUserRequest struct {
    Username string `validate:"min=3,max=40,regexp=^[a-zA-Z]$" db:'user_name'`
}
```

It will validate correctly.

**Comment by jameshartig** [comment]
@sharpner This is most likely because you have to use double quotes in tags. So `db:'user_name'` is breaking the whole tag. It should be `db:"user_name"`.

A quick test shows that validator is working fine as a second tag:

``` go
func (ms *MySuite) TestWithOtherTags(c *C) {
    type test struct {
        A string `db:"name" validate:"min=1"`
    }
    err := validator.Validate(Simple{})
    c.Assert(err, NotNil)
}
```

**Comment by sharpner** [comment]
wow forgot about that issue. 

No clue anymore :P but thanks for answering!
