### ISSUE TITLE
Update document examples

### ISSUE THREAD

**Issue by felixcheruiyot** [go-validator/validator#30]
It took me time to figure out that this does not work:

    if valid, err := validator.Validate(mystruct); !valid {
		fmt.Println("Error")
	}

I had to look at the code after 1 hour to realize it should be:

    if err := validator.Validate(mystruct); err != nil {
		fmt.Println("Error...")
	}

**Comment by jehna** [comment]
:+1:

**Comment by jameshartig** [comment]
Fixed with #31
