### ISSUE TITLE
Anonymous Embedded Struct

### ISSUE THREAD

**Issue by sundarv85** [go-validator/validator#45]
When I use validate in an anonymous embedded struct, then it is not validated on calling the parent struct validate function.

Is this expected?

**Comment by jameshartig** [comment]
Can you provide an example?

**Comment by vamsu** [comment]
Here is the scenario it doesn't work, with embedded structs. Looking at validation.go#valid() it should do something like http://stackoverflow.com/questions/29988632/go-reflection-with-interface-embedded-in-struct-how-to-detect-real-functions

package main

import (
    "encoding/json"
    "github.com/stretchr/testify/assert"
    "github.com/astaxie/beego/validation"
    "testing"
)

type Base struct {
    Foo string                `valid:"Required;MinSize(3)"`
}

type Sample struct {
    Base
}

func TestMe(t *testing.T) {
    payload := `{
        "foo" : "fo"
    }`
    sample := Sample{}

```
err := json.Unmarshal([]byte(payload), &sample)
assert.NoError(t, err)

validator := validation.Validation{}
validator.Valid(sample)
assert.Len(t, validator.Errors, 1)
```

}

You can workaround by calling
validator.Valid(sample.Foo)

**Comment by jameshartig** [comment]
@vamsu is this fixed by #54?

**Comment by Ferada** [comment]
@fastest963 I ran into the same issue, updated to master and it looks fixed to me at this moment.

**Comment by jameshartig** [comment]
This is fixed
