### ISSUE TITLE
Return value

### ISSUE THREAD

**Issue by Raggaer** [go-validator/validator#46]
On your example 

`if errs := validator.Validate(form); errs != nil {`

You say it returns an array of errors but it currently returns a single error... is this intended or I am missing something?

Also is it possible to set a custom field name for the returned error?

**Comment by jameshartig** [comment]
Validate returns an ErrorsMap that you can cast `errs` to if you wish to inspect each field's errors. See how we do it in the tests: https://github.com/go-validator/validator/blob/v2/validator_test.go#L64

> Also is it possible to set a custom field name for the returned error?

What do you mean?
