### ISSUE TITLE
Bool Pointer Zero Value

### ISSUE THREAD

**Issue by 0x7061** [go-validator/validator#51]
Hi,

why is `false` a zero value for a bool pointer? I'm using a pointer on purpose so I can distinguish between ommited struct fields and set fields in my HTTP PATCH route.

When passing `false` I'm getting: "Enabled: zero value".

Any idea?

**Comment by ekote** [comment]
I have the same situation.

**Comment by 0x7061** [comment]
@ekote I switched to go-playground's validator. It supports all of that!

**Comment by ekote** [comment]
Thanks @codepushr!

**Comment by jameshartig** [comment]
The `nonzero` builtin is just a convenience handler and I would argue that majority of people expect the nonzero to work on the pointer's reference and not the pointer itself. That said, you can easily do:

```
type OptionalBool struct {
	Enabled *bool `validate:"nonnil"`
}

func main() {
	validator.SetValidationFunc("nonnil", func(v interface{}, param string) error {
		if v == nil {
			return validator.ErrInvalid
		}
		return nil
	})
}
```
That will complain about the nil pointer.

Sorry for the delay on this.
