### ISSUE TITLE
regexp validation not working

### ISSUE THREAD

**Issue by lucasvanhalst** [go-validator/validator#53]
Not sure what I am doing wrong but I cannot get regexp validation working.

Consider this type: 
```go

type EmailAddress struct {
	EmailAddress string `json:"emailaddress" validate:"regexp=^[a-z0-9._%+\-]+@[a-z0-9.\-]+\.[a-z]{2,4}$"`
	Label        string `json:"label" validate:"regexp=^[a-zA-Z\d\-_\s]{2,50}$"`
}
```
I would expect it to give an error when I supply it with this:

```go
email := EmailAddress{
	EmailAddress: "!@#$%$^#&^**(&", // just random invalid characters to be sure it triggers an error in the validation
	Label: "!@#$%$}",
}
log.Debug(validator.Validate(email))
```
Instead what I get is nil. min/max validations work fine, but regexp doesn't seem to work at all. Am I doing something wrong or is there something else I'm missing?

I'm using the v2 branch.

**Comment by stewbawka** [comment]
Also having this issue using same regexp

**Comment by stewbawka** [comment]
Have gotten the equivalent working by creating a custom validator based on the example code

**Comment by jameshartig** [comment]
The issue here is that you need to double escape the regex escapes, just like you would if they were a string with double quotes.
```
type EmailAddress struct {
	EmailAddress string `json:"emailaddress" validate:"regexp=^[a-z0-9._%+\\-]+@[a-z0-9.\\-]+\\.[a-z]{2,4}$"`
	Label        string `json:"label" validate:"regexp=^[a-zA-Z\\d\\-_\\s]{2,50}$"`
}
```
The above struct tags fixes your issue.

Additionally, if you run `go tool vet` it'll complain about these problems:
```Finished running tool: go tool vet
struct field tag `json:"emailaddress" validate:"regexp=^[a-z0-9._%+\-]+@[a-z0-9.\-]+\\.[a-z]{2,4}$"` not compatible with reflect.StructTag.Get: bad syntax for struct tag value
struct field tag `json:"label" validate:"regexp=^[a-zA-Z\d\-_\s]{2,50}$"` not compatible with reflect.StructTag.Get: bad syntax for struct tag value
```
