### ISSUE TITLE
interface is nil, not string

### ISSUE THREAD

**Issue by dejjan** [go-validator/validator#58]
Hi, I am having some trouble when using validation package. It's return error 
**Handler crashed with error interface conversion: interface is nil, not string**

it's occurred because some client forgot or maybe test the API validation with skipped one or more required parameters and I want this handled by validator package.

This is the details. may you help me ?. Thanks anyway

```
type ParamRequest struct {
	PhoneNumber string `validate:"nonzero"`
	ItemCode    string `validate:"nonzero"`
}

func (c *TopupAlloperatorApiController) Post() {
 interf := make(map[string]interface{})
 json.Unmarshal(c.Ctx.Input.RequestBody, &interf)
 ve := ParamRequest{
    PhoneNumber: interf["PhoneNumber"].(string), 
    ItemCode:    interf["ItemCode"].(string),    
 }
}
```

**Comment by jameshartig** [comment]
@dejjan I don't see in your example where you're making the call to the validator API. Is the problem with `interf["PhoneNumber"].(string)` or `interf["ItemCode"].(string)` because that's what it sounds like but that isn't part of the validator code.
