### ISSUE TITLE
Web-Validators: email, url, phone, html

### ISSUE THREAD

**Issue by zoonman** [go-validator/validator#59]
This is very simple validator and needs improvements for building modern web-application.
It must have the following validators: 
- [ ] email
- [ ] url
- [ ] phone
- [ ] html (the given string is a valid html)
- [ ] ipv4
- [ ] ipv6
- [ ] isbn
- [ ] currency
- [ ] ascii
- [ ] fqdn
- [ ] mac address

**Comment by ianrose14** [comment]
"must"?

**Comment by zoonman** [comment]
If someone will look for real validator, check out this one https://github.com/asaskevich/govalidator
