### ISSUE TITLE
Every thought of adding a validator for email format?

### ISSUE THREAD

**Issue by wunderkind2k1** [go-validator/validator#61]
I suppose this could be very useful in a lot of projects - among others like credit-card, zip codes and so on.

I understand that the user can easily write that validations on his/ her own but this means its done repeatedly in a lot of projects.

**Comment by jameshartig** [comment]
This was not added to the default list since email validations vary widely. There are numerous different regexes that no one agrees on. Instead of copying/pasting code per project, you can have a single project (library) that adds your own custom validators, then use that everywhere.

**Comment by wunderkind2k1** [comment]
Ok. good point. thanks.
