### ISSUE TITLE
Return all errors from error() not just first?

### ISSUE THREAD

**Issue by PatrickWalker** [go-validator/validator#68]
Hey,

Just wondering if there would be any interest in returning a newline or space seperated string containing all the errors in the map rather than just the first one range hits?

**Comment by PatrickWalker** [comment]
https://github.com/go-validator/validator/pull/69 
if that helps describe the change

**Comment by robovery** [comment]
I would be extremely interested in that. Currently I have to iterate over the map and build my own error. This falls apart for me when I use the pkg/errors error and I have no control over how it builds the error.

**Comment by robovery** [comment]
this was completed in https://github.com/go-validator/validator/pull/83 and https://github.com/go-validator/validator/pull/84.
