### ISSUE TITLE
Use json tag as key in the ErrorMap  when possible

### ISSUE THREAD

**Issue by christophe-dufour** [go-validator/validator#70]
Let's imagine I have a payload to validate like this:

```
type Person struct{
   Name string `validate:"nonzero" json:"name"`
   Age    int `validate:"min=18" json:"age"`
}
```

If I receive a JSON payload like this:
```
{"name":"John","age":10}
```

I would like to get an error telling me that `age` is supposed to be at least 18. But in the ErrorMap the key is `Age`

And once I have the `Age` it's kind of complicated to parse my struct again in order to get the json tag again.

Do you guys think we could configure the validator to parse and use the json tag in the payload?

**Comment by robovery** [comment]
completed in https://github.com/go-validator/validator/pull/85
