### ISSUE TITLE
当我写了一个正则校验.  在这个参数没传的情况下也会报错(这个参数允许为空)

### ISSUE THREAD

**Issue by ywdhzxf** [go-validator/validator#87]
当我写了一个密码验证
```
Password   string   `json:"password" validate:"regexp=^[a-zA-Z0-9]{8,15}$"`
```
表明了这个参数不会必传, 然后在请求传空或者不传的情况下,  调用validator.Validate就会报错, 建议加一个判空操作, 当参数不是必传且为空时, 可以不走正则校验

**Comment by jameshartig** [comment]
I think you can instead make the regex be `^(|[a-zA-Z0-9]{8,15})$` and that'll allow empty or your regex. Let me know if that doesn't work.

**Comment by ywdhzxf** [comment]
This is feasible, but I found another problem. When the regular contains {8,19}, error password: unknown tag will be triggered
```
type param struct {
	Name     string `json:"name" validate:"nonzero"`
	Password string `json:"password" validate:"regexp=^(|[a-zA-Z0-9]{8,19})$"`
	//Password string `json:"password" validate:"regexp=^(|[a-zA-Z0-9]{8})$"`
}
var request = param{Name:"fei", Password:""}
if err := validator.Validate(request); err != nil {
	fmt.Println(err.Error())    // Error: Password: unknown tag
}

```

**Comment by jameshartig** [comment]
Escape the , with a \. Like `regexp=^(|[a-zA-Z0-9]{8\,19})$`

I'll update the README to clarify this

**Comment by shixiaofeia** [comment]
In this way, the editor will explode syntax errors and will not take effect
![image](https://user-images.githubusercontent.com/63829677/79530232-5907e100-80a1-11ea-803f-c62e23459905.png)

**Comment by jameshartig** [comment]
Ah, apparently there needs to be 2 slashes. Like: `regexp=^(|[a-zA-Z0-9]{8\\,19})$`
Source: https://github.com/go-validator/validator/issues/56#issuecomment-322191094

**Comment by shixiaofeia** [comment]
OK, thank you
