### ISSUE TITLE
Trouble getting regex validator working

### ISSUE THREAD

**Issue by JaeTLDR** [go-validator/validator#92]
regexp validator not working using lookaheads.

using the following struct i cannot get the validator to work 
```
type pwd struct {
	Password string `validate:"regexp=^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[.!@#\\$%\\^&\\*])(?=.{8\\,})"`
}
```
Expected result: password must have 1 of each lower, upper numeral and special , and be atleast 8 characters long 

Actual result: either no validation occurs or `Password (bad parameter)` is returned 

Thanks

**Comment by JaeTLDR** [comment]
test program used
``` golang
package main

import (
	"flag"
	"fmt"

	"gopkg.in/validator.v2"
)

type pwd struct {
	Password string `validate:"regexp=^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[.!@#\\$%\\^&\\*])(?=.{8\\,})"`
}

var p = flag.String("p", "password", "help text")

func main() {
	flag.Parse()
	x := pwd{Password: *p}
	fmt.Println(x)
	if errs := validator.Validate(x); errs != nil {
		errv := errs.(validator.ErrorMap)
		for f, e := range errv {
			fmt.Printf("%s (%v)", f, e)
		}
	}
}
```

**Comment by jameshartig** [comment]
@JaeTLDR it looks like that pattern fails with the `regexp` package:
https://play.golang.org/p/x8iqZjPJzdY
